name: viewplanning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy=1.7
  - pyvista=0.34
  - pyembree=0.1.6
  - trimesh=3.12
  - rtree=1.0
  - pytest=7.1
  - matplotlib=3.5
  - shapely=1.8
  - pymongo=4.1
  - pyyaml=6.0
  - geopandas=0.9
