name: viewplanning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scipy
  - pyvista
  - pymeshfix
  - pyembree
  - trimesh
  - rtree
  - pytest
  - matplotlib
  - shapely
  - pymongo
  - pyyaml
  - geopandas
  - networkx
  - numpy=1.22
  - psutil
  - tqdm
