from .bodySampleStrategy import BodySampleStrategy
from .faceSampleStrategy import FaceSampleStrategy
from .globalPerimeterWeightedFaceSampleStrategy import GlobalPerimeterWeightedFaceSampleStrategy
from .pointSampleStrategy import PointSampleStrategy
from .maxAreaEdgeSampleStrategy import MaxAreaEdgeSampleStrategy
from .maxAreaPolygonSampleStrategy import MaxAreaPolygonSampleStrategy
from .edge3dSampleStrategy import Edge3dSampleStrategy
