database:
  mongo:
    host: localhost
    port: 27017
    db: view_planning
    user: ""
    password: ""
  experiments:
    type: json
    location: data/experiments.json
  regions:
    type: json
    location: data/regions.json
  results:
    type: json
    location: data/results.json
intersection:
  type: 'memory'
  folder: data/veiwRegions/cliques/
process:
  timeout: 21600
  multithreading: True
logging:
  level: 'INFO'
  handlers:
    - out: 'stdout'
      name: 'info'
      mode: 'a'
      format: '%(asctime)s %(relativeCreated)6d %(threadName)s %(levelname)s %(message)s'
      level: 'INFO'
    - out: 'stderr'
      name: 'error'
      mode: 'a'
      format: '%(asctime)s %(relativeCreated)6d %(threadName)s %(levelname)s %(message)s'
      level: 'WARNING'
    - out: 'log.txt'
      name: 'file'
      mode: 'a'
      format: '%(asctime)s %(relativeCreated)6d %(threadName)s %(levelname)s %(message)s'
      level: 'INFO'
